apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::353692670264:user/jenkins
      username: jenkins
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::353692670264:role/UdacityCapStone-Cluster-Worker-NodeInstanceRole-1KQJ6DCMC7B6D
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
